spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
kakao:
  auth-url: https://kauth.kakao.com/oauth/token
  user-api-url: https://kapi.kakao.com/v2/user/me
  restapi-key: ${REST_API_KEY}
  redirect-url: ${PROD_REDIRECT_URL}
  logout-url: ${PROD_LOGOUT_URL}
error:
  webhook:
    url: ${PROD_WEBHOOK_URL}

cloud:
  naver:
    credentials:
      end-point: "https://kr.object.ncloudstorage.com"
      region: "kr-standard"
      access-key: ${OBJECT_STORAGE_ACCESS_KEY}
      secret-key: ${OBJECT_STORAGE_SECRET_KEY}
      bucket: "praise-up-image"