spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
kakao:
  authUrl: https://kauth.kakao.com/oauth/token
  userApiUrl: https://kapi.kakao.com/v2/user/me
  restapiKey: 2c6ce0e44b0542de868a8eb75b80a84a
  redirectUrl: http://localhost:8080/praise-up/api/v1/sign-up
  logout-url: https://kauth.kakao.com/oauth/logout?client_id=2c6ce0e44b0542de868a8eb75b80a84a
  logout_redirect_uri: http://localhost:8080/praise-up/api/v1/logout
error:
  webhook:
    url: https://hooks.slack.com/services/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
cloud:
  naver:
    credentials:
      end-point: "https://kr.object.ncloudstorage.com"
      region: "kr-standard"
      access-key: 0Y9zGcnhx78p02I5SvVW
      secret-key: mQTBmlEkck4riU1l64Vkh3xBKyMEfee43Arf3YOn
      bucket: "praise-up-image"